[versions]
assertj = "3.23.1"
gson = "2.9.0"
jackson = "2.13.3"
jqwik = "1.6.5"
junit = "5.9.0-M1"
mockito = "4.6.1"
moshi = "1.13.0"
retrofit = "2.9.0"
wiremock = "2.33.2"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
wiremock = { module = "com.github.tomakehurst:wiremock-jre8", version.ref = "wiremock" }

[bundles]
junit = ["junit-jupiter", "junit-vintage"]
mockito = ["mockito-inline", "mockito-junit"]
moshi = ["moshi-adapters", "moshi"]

[plugins]
versions = { id = "com.github.ben-manes.versions", version = "0.42.0" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version = "0.5.1" }
